version: 0.2

phases:
  install:
    commands:
      - mkdir myuw_env
      - cp -R . /tmp/myuw_env
      - cp -R /tmp/myuw_env ./myuw_env
      - rm -rf myuw_env/myuw_env
      - pip install virtualenv
      - virtualenv myuw_env
      - cd myuw_env
      - . bin/activate
      - pip install -r requirements.txt
      - pip install coverage
      - pip install python-coveralls
      - pip install pycodestyle
  pre_build:
    commands:
      - cp travis-ci/manage.py manage.py
      - python manage.py migrate
  build:
    commands:
      - python manage.py test myuw
