version: 0.2

phases:
  install:
    commands:
      - pip install virtualenv
      - apt-get update && apt-get install -y libxml2-dev libxmlsec1-dev
      - pip install -r requirements.txt
      - pip install coverage
      - pip install python-coveralls
      - pip install pycodestyle
  pre_build:
    commands:
      - django-admin.py startproject project .
      - rm project/settings.py && rm project/urls.py
      - cp travis-ci/settings.py project/settings.py && cp travis-ci/urls.py project/urls.py
      - python manage.py migrate
  build:
    commands:
      - pycodestyle myuw/ --exclude=migrations,myuw/static
      - python manage.py test myuw
