version: 0.2

phases:
  install:
    commands:
      - cp -R . /tmp/myuw_env/
      - pip install virtualenv
      - virtualenv /tmp/myuw_env
      - cd /tmp/myuw_env
      - . bin/activate
      - apt-get update && apt-get install -y libxml2-dev libxmlsec1-dev
      - pip install -r requirements.txt
      - pip install coverage
      - pip install python-coveralls
      - pip install pycodestyle
  pre_build:
    commands:
      - django-admin.py startproject project .
      - rm project/settings.py && rm project/urls.py
      - cp docker/settings.py project/settings.py && cp docker/urls.py project/urls.py
      - python manage.py migrate
  build:
    commands:
      - pycodestyle myuw/ --exclude=migrations,myuw/static
      - python manage.py test myuw
artifacts:
  files:
    - '*'
  discard-paths: yes
  base-directory: /tmp/myuw_env/
