from django.test import TestCase
from myuw_mobile.test.dao.course_color import TestCourseColors
from myuw_mobile.test.dao.registered_term import TestRegisteredTerm
from myuw_mobile.test.dao.schedule import TestSchedule
from myuw_mobile.test.dao.notice import TestNotce
from myuw_mobile.test.models import TestUserNotices
from myuw_mobile.test.dao.term import TestTerm
from myuw_mobile.test.userservice_validation import TestValidation
from myuw_mobile.test.dao.hfs import TestHFS
from myuw_mobile.test.dao.library import TestLibrary
from myuw_mobile.test.dao.building import TestBuildings
