# Generated by Django 3.2.20 on 2023-09-01 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BannerMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('message_title', models.TextField()),
                ('message_body', models.TextField()),
                ('is_published', models.BooleanField(default=False)),
                ('affiliation', models.CharField(max_length=80, null=True)),
                ('pce', models.BooleanField(null=True)),
                ('campus', models.CharField(max_length=8, null=True)),
                ('group_id', models.CharField(max_length=200, null=True)),
                ('added_by', models.CharField(max_length=50)),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('preview_id', models.SlugField(null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CampusBuilding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=16)),
                ('number', models.CharField(db_index=True, max_length=16)),
                ('latitude', models.CharField(max_length=32)),
                ('longitude', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=96)),
            ],
        ),
        migrations.CreateModel(
            name='MyuwNotice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(null=True)),
                ('content', models.TextField(null=True)),
                ('notice_type', models.TextField(max_length=128)),
                ('notice_category', models.TextField(max_length=128)),
                ('is_critical', models.BooleanField(default=False)),
                ('start', models.DateTimeField(default=None, null=True)),
                ('end', models.DateTimeField(default=None, null=True)),
                ('start_week', models.SmallIntegerField(default=0)),
                ('duration', models.PositiveSmallIntegerField(default=0)),
                ('is_winter', models.BooleanField(default=False)),
                ('is_spring', models.BooleanField(default=False)),
                ('is_autumn', models.BooleanField(default=False)),
                ('is_summer_a', models.BooleanField(default=False)),
                ('is_summer_b', models.BooleanField(default=False)),
                ('last_edit_by', models.CharField(max_length=128)),
                ('last_edit_date', models.DateTimeField(auto_now=True)),
                ('is_seattle', models.BooleanField(default=False)),
                ('is_tacoma', models.BooleanField(default=False)),
                ('is_bothell', models.BooleanField(default=False)),
                ('is_alumni', models.BooleanField(default=False)),
                ('is_applicant', models.BooleanField(default=False)),
                ('is_grad', models.BooleanField(default=False)),
                ('is_grad_c2', models.BooleanField(default=False)),
                ('is_intl_stud', models.BooleanField(default=False)),
                ('not_intl_stud', models.BooleanField(default=False)),
                ('is_pce', models.BooleanField(default=False)),
                ('is_student', models.BooleanField(default=False)),
                ('is_undergrad', models.BooleanField(default=False)),
                ('is_undergrad_c2', models.BooleanField(default=False)),
                ('is_fyp', models.BooleanField(default=False)),
                ('is_past_student', models.BooleanField(default=False)),
                ('is_clinician', models.BooleanField(default=False)),
                ('is_employee', models.BooleanField(default=False)),
                ('is_faculty', models.BooleanField(default=False)),
                ('is_instructor', models.BooleanField(default=False)),
                ('is_past_employee', models.BooleanField(default=False)),
                ('is_retiree', models.BooleanField(default=False)),
                ('is_staff_employee', models.BooleanField(default=False)),
                ('is_stud_employee', models.BooleanField(default=False)),
                ('target_group', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PopularLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('affiliation', models.CharField(max_length=256, null=True)),
                ('pce', models.BooleanField(null=True)),
                ('campus', models.CharField(max_length=8, null=True)),
                ('url', models.CharField(max_length=512)),
                ('label', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ResCategoryLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=150)),
                ('title', models.CharField(max_length=150)),
                ('affiliation', models.CharField(max_length=80, null=True)),
                ('pce', models.BooleanField(null=True)),
                ('campus', models.CharField(max_length=8, null=True)),
                ('category_id', models.CharField(max_length=80)),
                ('category_name', models.CharField(max_length=80)),
                ('sub_category', models.CharField(max_length=80)),
                ('subcategory_id', models.CharField(max_length=80, null=True)),
                ('new_tab', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'myuw_res_category_links',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uwnetid', models.CharField(db_index=True, max_length=128, unique=True)),
                ('last_visit', models.DateTimeField()),
            ],
            options={
                'db_table': 'myuw_mobile_user',
            },
        ),
        migrations.CreateModel(
            name='VisitedLinkNew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=512)),
                ('label', models.CharField(max_length=50, null=True)),
                ('is_anonymous', models.BooleanField(default=True)),
                ('is_student', models.BooleanField(default=False)),
                ('is_undegrad', models.BooleanField(default=False)),
                ('is_grad_student', models.BooleanField(default=False)),
                ('is_employee', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_faculty', models.BooleanField(default=False)),
                ('is_seattle', models.BooleanField(default=False)),
                ('is_tacoma', models.BooleanField(default=False)),
                ('is_bothell', models.BooleanField(default=False)),
                ('is_pce', models.BooleanField(default=False)),
                ('is_student_employee', models.BooleanField(default=False)),
                ('is_intl_stud', models.BooleanField(default=False)),
                ('visit_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myuw.user')),
            ],
        ),
        migrations.CreateModel(
            name='SeenRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(db_index=True)),
                ('quarter', models.CharField(db_index=True, max_length=10)),
                ('summer_term', models.CharField(max_length=1)),
                ('first_seen_date', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myuw.user')),
            ],
            options={
                'db_table': 'myuw_mobile_seenregistration',
            },
        ),
        migrations.CreateModel(
            name='ResourceCategoryPin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_category_id', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myuw.user')),
            ],
        ),
        migrations.CreateModel(
            name='MigrationPreference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_onboard_message', models.BooleanField(default=True)),
                ('display_pop_up', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myuw.user')),
            ],
            options={
                'db_table': 'migration_preference',
            },
        ),
        migrations.CreateModel(
            name='UserNotices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notice_hash', models.CharField(max_length=32)),
                ('first_viewed', models.DateTimeField(auto_now_add=True)),
                ('marked_read', models.DateTimeField(null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('notice_cattype', models.CharField(blank=True, max_length=256, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myuw.user')),
            ],
            options={
                'db_table': 'myuw_mobile_usernotices',
                'unique_together': {('notice_hash', 'user')},
            },
        ),
        migrations.CreateModel(
            name='UserCourseDisplay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField()),
                ('quarter', models.CharField(max_length=10)),
                ('section_label', models.CharField(max_length=64)),
                ('color_id', models.PositiveSmallIntegerField()),
                ('pin_on_teaching_page', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myuw.user')),
            ],
            options={
                'db_table': 'user_course_display_pref',
                'ordering': ['section_label'],
                'unique_together': {('user', 'section_label')},
                'index_together': {('user', 'section_label'), ('user', 'year', 'quarter')},
            },
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(db_index=True)),
                ('quarter', models.CharField(db_index=True, max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myuw.user')),
            ],
            options={
                'db_table': 'myuw_known_instructors',
                'unique_together': {('user', 'year', 'quarter')},
            },
        ),
        migrations.CreateModel(
            name='HiddenLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=512)),
                ('url_key', models.SlugField(max_length=40)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myuw.user')),
            ],
            options={
                'unique_together': {('url_key', 'user')},
            },
        ),
        migrations.CreateModel(
            name='CustomLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=512)),
                ('label', models.CharField(max_length=50, null=True)),
                ('url_key', models.SlugField(max_length=40)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myuw.user')),
            ],
            options={
                'unique_together': {('url_key', 'user')},
            },
        ),
    ]
