# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-28 21:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=6)),
                ('latititude', models.CharField(max_length=40)),
                ('longitude', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'myuw_mobile_building',
            },
        ),
        migrations.CreateModel(
            name='CourseColor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regid', models.CharField(db_index=True, max_length=32)),
                ('year', models.PositiveSmallIntegerField(db_index=True)),
                ('quarter', models.CharField(db_index=True, max_length=10)),
                ('curriculum_abbr', models.CharField(max_length=10)),
                ('course_number', models.CharField(max_length=3)),
                ('section_id', models.CharField(max_length=2)),
                ('is_active', models.BooleanField()),
                ('color_id', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'myuw_mobile_coursecolor',
            },
        ),
        migrations.CreateModel(
            name='ResCategoryLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=150)),
                ('title', models.CharField(max_length=150)),
                ('affiliation', models.CharField(max_length=80, null=True)),
                ('campus', models.CharField(max_length=8, null=True)),
                ('category_id', models.CharField(max_length=80)),
                ('category_name', models.CharField(max_length=80)),
                ('sub_category', models.CharField(max_length=80)),
                ('new_tab', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'myuw_res_category_links',
            },
        ),
        migrations.CreateModel(
            name='SeenRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(db_index=True)),
                ('quarter', models.CharField(db_index=True, max_length=10)),
                ('summer_term', models.CharField(max_length=1)),
                ('first_seen_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'myuw_mobile_seenregistration',
            },
        ),
        migrations.CreateModel(
            name='StudentAccountsBalances',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_number', models.CharField(db_index=True, max_length=10, unique=True)),
                ('employee_id', models.CharField(blank=True, db_index=True, max_length=10, null=True)),
                ('asof_datetime', models.DateTimeField()),
                ('is_am', models.BooleanField(default=True)),
                ('husky_card', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('residence_hall_dining', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
            ],
            options={
                'db_table': 'myuw_mobile_studentaccountsbalances',
            },
        ),
        migrations.CreateModel(
            name='TuitionDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_stored', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
            ],
            options={
                'db_table': 'myuw_mobile_tuitiondate',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uwnetid', models.SlugField(max_length=16, unique=True)),
                ('uwregid', models.CharField(db_index=True, max_length=32, null=True, unique=True)),
                ('last_visit', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'myuw_mobile_user',
            },
        ),
        migrations.CreateModel(
            name='UserMigrationPreference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, max_length=20, unique=True)),
                ('use_legacy_site', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserNotices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notice_hash', models.CharField(max_length=32)),
                ('first_viewed', models.DateTimeField(auto_now_add=True)),
                ('marked_read', models.DateTimeField(null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('notice_cattype', models.CharField(blank=True, max_length=256, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myuw.User')),
            ],
            options={
                'db_table': 'myuw_mobile_usernotices',
            },
        ),
        migrations.AddField(
            model_name='tuitiondate',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='myuw.User'),
        ),
        migrations.AddField(
            model_name='seenregistration',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myuw.User'),
        ),
        migrations.AlterUniqueTogether(
            name='usernotices',
            unique_together=set([('notice_hash', 'user')]),
        ),
    ]
