# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-14 00:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myuw', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('eligibility_type', models.CharField(max_length=32)),
                ('eligibility_data', models.CharField(max_length=255)),
                ('message_title', models.TextField()),
                ('message_body', models.TextField()),
            ],
        ),
    ]
