# Copyright 2021 UW-IT, University of Washington
# SPDX-License-Identifier: Apache-2.0

# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-04 20:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myuw', '0002_bannermessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='rescategorylink',
            name='pce',
            field=models.NullBooleanField(),
        ),
    ]
