# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-28 16:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myuw', '0002_affililationlink_popularlink_visitedlink'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField()),
                ('label', models.CharField(max_length=50, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myuw.User')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='customlink',
            unique_together=set([('user', 'url')]),
        ),
    ]
