# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-16 22:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myuw', '0003_rescategorylink_pce'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannermessage',
            name='added_by',
            field=models.CharField(default='import_no_user', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bannermessage',
            name='added_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bannermessage',
            name='affiliation',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='bannermessage',
            name='campus',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='bannermessage',
            name='pce',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='bannermessage',
            name='eligibility_data',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bannermessage',
            name='eligibility_type',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
