# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-17 19:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myuw', '0003_rescategorylink_pce'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=512)),
                ('label', models.CharField(max_length=50, null=True)),
                ('url_key', models.SlugField(max_length=40)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myuw.User')),
            ],
        ),
        migrations.CreateModel(
            name='HiddenLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=512)),
                ('url_key', models.SlugField(max_length=40)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myuw.User')),
            ],
        ),
        migrations.CreateModel(
            name='PopularLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('affiliation', models.CharField(max_length=80, null=True)),
                ('pce', models.NullBooleanField()),
                ('campus', models.CharField(max_length=8, null=True)),
                ('url', models.CharField(max_length=512)),
                ('label', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='hiddenlink',
            unique_together=set([('url_key', 'user')]),
        ),
        migrations.AlterUniqueTogether(
            name='customlink',
            unique_together=set([('url_key', 'user')]),
        ),
    ]
