# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-28 23:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myuw', '0003_auto_20170428_0926'),
    ]

    operations = [
        migrations.CreateModel(
            name='HiddenLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myuw.User')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='hiddenlink',
            unique_together=set([('user', 'url')]),
        ),
    ]
