# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-22 15:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myuw', '0004_adding_link_models'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bannermessage',
            name='eligibility_data',
        ),
        migrations.RemoveField(
            model_name='bannermessage',
            name='eligibility_type',
        ),
        migrations.AddField(
            model_name='bannermessage',
            name='added_by',
            field=models.CharField(default='import_no_user', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bannermessage',
            name='added_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bannermessage',
            name='affiliation',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='bannermessage',
            name='campus',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='bannermessage',
            name='group_id',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bannermessage',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bannermessage',
            name='pce',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='bannermessage',
            name='preview_id',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='bannermessage',
            name='end',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='bannermessage',
            name='start',
            field=models.DateTimeField(),
        ),
    ]
