# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-24 19:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myuw', '0005_banner_messages_affiliation_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeenInstructor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uwnetid', models.SlugField(max_length=16)),
                ('year', models.PositiveSmallIntegerField(db_index=True)),
                ('quarter', models.CharField(db_index=True, max_length=10)),
            ],
        ),
    ]
