# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-21 22:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myuw', '0006_seeninstructor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seeninstructor',
            name='user',
        ),
        migrations.AddField(
            model_name='seeninstructor',
            name='uwnetid',
            field=models.SlugField(default='test', max_length=16, unique=True),
            preserve_default=False,
        ),
    ]
