# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-24 22:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myuw', '0007_new_visitedlink'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VisitedLink',
        ),
    ]
