# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-22 00:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myuw', '0007_auto_20170721_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seeninstructor',
            name='uwnetid',
            field=models.SlugField(max_length=16),
        ),
    ]
