# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-29 23:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myuw', '0008_user_course_display'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usercoursedisplay',
            unique_together=set([]),
        ),
    ]
