# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-10 17:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myuw', '0008_user_course_display'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CourseColor',
        ),
        migrations.RemoveField(
            model_name='user',
            name='uwregid',
        ),
        migrations.AlterField(
            model_name='user',
            name='last_visit',
            field=models.DateTimeField(),
        ),
        migrations.AddField(
            model_name='migrationpreference',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myuw.User'),
        ),
    ]
