# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-12 21:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myuw', '0009_migration_preference'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceCategoryPin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_category_id', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myuw.User')),
            ],
        ),
        migrations.AddField(
            model_name='rescategorylink',
            name='subcategory_id',
            field=models.CharField(default='', max_length=80),
            preserve_default=False,
        ),
    ]
