# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-11 23:00
from __future__ import unicode_literals
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myuw', '0010_rescategorylink_subcategory_id'),
        ('myuw', '0009_migration_preference'),
    ]

    operations = [
    ]
