# Copyright 2021 UW-IT, University of Washington
# SPDX-License-Identifier: Apache-2.0

# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-02 00:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myuw', '0011_merge_20180411_1600'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyuwNotice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(null=True)),
                ('content', models.TextField(null=True)),
                ('notice_type', models.TextField(max_length=128)),
                ('notice_category', models.TextField(max_length=128)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField(null=True)),
                ('last_edit_by', models.CharField(max_length=16)),
                ('last_edit_date', models.DateTimeField(auto_now=True)),
                ('is_seattle', models.BooleanField(default=False)),
                ('is_tacoma', models.BooleanField(default=False)),
                ('is_bothell', models.BooleanField(default=False)),
                ('is_alumni', models.BooleanField(default=False)),
                ('is_applicant', models.BooleanField(default=False)),
                ('is_grad', models.BooleanField(default=False)),
                ('is_grad_c2', models.BooleanField(default=False)),
                ('is_pce', models.BooleanField(default=False)),
                ('is_student', models.BooleanField(default=False)),
                ('is_undergrad', models.BooleanField(default=False)),
                ('is_undergrad_c2', models.BooleanField(default=False)),
                ('is_fyp', models.BooleanField(default=False)),
                ('is_past_student', models.BooleanField(default=False)),
                ('is_clinician', models.BooleanField(default=False)),
                ('is_employee', models.BooleanField(default=False)),
                ('is_faculty', models.BooleanField(default=False)),
                ('is_instructor', models.BooleanField(default=False)),
                ('is_past_employee', models.BooleanField(default=False)),
                ('is_retiree', models.BooleanField(default=False)),
                ('is_staff_employee', models.BooleanField(default=False)),
                ('is_stud_employee', models.BooleanField(default=False)),
            ],
        ),
    ]
