# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-28 20:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myuw', '0012_myuwnotice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(db_index=True)),
                ('quarter', models.CharField(db_index=True, max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myuw.User')),
            ],
            options={
                'db_table': 'myuw_known_instructors',
            },
        ),
        migrations.AlterUniqueTogether(
            name='instructor',
            unique_together=set([('user', 'year', 'quarter')]),
        ),
    ]
