# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-17 18:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myuw', '0013_known_instructors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='popularlink',
            name='affiliation',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='visitedlinknew',
            name='is_intl_stud',
            field=models.BooleanField(default=False),
        ),
    ]
