# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-23 20:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myuw', '0014_intl_stud_links'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='popularlink',
            name='intl_stud',
        ),
        migrations.AlterField(
            model_name='popularlink',
            name='affiliation',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
