# Generated by Django 2.0.13 on 2019-12-03 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myuw', '0015_intl_stud_notice'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuwnotice',
            name='target_group',
            field=models.TextField(blank=True, null=True),
        ),
    ]
