# Generated by Django 2.0.13 on 2020-04-02 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myuw', '0016_myuw_notice_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuwnotice',
            name='is_critical',
            field=models.BooleanField(default=False),
        ),
    ]
