# Generated by Django 2.0.13 on 2020-03-12 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myuw', '0016_myuw_notice_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uwnetid',
            field=models.SlugField(max_length=32, unique=True),
        ),
    ]
