# Copyright 2021 UW-IT, University of Washington
# SPDX-License-Identifier: Apache-2.0

# Generated by Django 2.0.13 on 2020-06-04 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myuw', '0017_critical_notice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuwnotice',
            name='last_edit_by',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='user',
            name='uwnetid',
            field=models.CharField(db_index=True, max_length=128, unique=True),
        ),
    ]
