# Generated by Django 2.0.13 on 2020-03-26 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myuw', '0017_netidlen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uwnetid',
            field=models.SlugField(max_length=16, unique=True),
        ),
    ]
