# Generated by Django 2.0.13 on 2020-09-19 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myuw', '0018_netid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seenregistration',
            name='first_seen_date',
            field=models.DateTimeField(),
        ),
    ]
