# Generated by Django 2.2.24 on 2021-11-09 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myuw', '0019_seenregistration'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampusBuilding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=10)),
                ('number', models.CharField(db_index=True, max_length=10)),
                ('latititude', models.CharField(max_length=40)),
                ('longitude', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
