# Generated by Django 3.2.19 on 2023-05-26 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myuw', '0020_campus_building'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Building',
        ),
        migrations.AddField(
            model_name='myuwnotice',
            name='duration',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='myuwnotice',
            name='is_autumn',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='myuwnotice',
            name='is_spring',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='myuwnotice',
            name='is_summer_a',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='myuwnotice',
            name='is_summer_b',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='myuwnotice',
            name='is_winter',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='myuwnotice',
            name='not_intl_stud',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='myuwnotice',
            name='start_week',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='myuwnotice',
            name='start',
            field=models.DateTimeField(null=True, default=None),
        ),
        migrations.AlterField(
            model_name='myuwnotice',
            name='end',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
