# Generated by Django 3.2.18 on 2023-08-24 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myuw', '0021_myuwnotice_recur'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='migrationpreference',
            name='use_legacy_site',
        ),
    ]
