# Generated by Django 3.2.18 on 2023-08-26 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myuw', '0022_remove_use_legacy'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TuitionDate',
        ),
    ]
