# Generated by Django 5.2.13 on 2026-05-29 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myuw', '0023_delete_tuitiondate'),
    ]

    operations = [
        migrations.AddField(
            model_name='campusbuilding',
            name='location_url',
            field=models.CharField(max_length=256, null=True, blank=True),
        ),
    ]
